[package]
name = "crab-scheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"

[dev-dependencies]
paste = "1.0.12"


[lib]
path = "src/lib.rs"

[[bin]]
name = "crab-scheme"